# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
#   http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

---
- name: Ensure needed repositories are enabled (EPEL)
  package: name=epel-release

- name: Ensure needed repositories are enabled (Cloud SIG)
  package: name=centos-release-openstack-mitaka

- name: Ensure needed repositories are enabled (DCI)
  package: name=https://packages.distributed-ci.io/dci-release.el7.noarch.rpm


- name: Ensure python-tripleo-helper is installed
  package: name=python-tripleo-helper

- name: Generate the chainsaw-ovb configuration file
  template: src=chainsaw.conf
            dest=/etc/chainsaw.conf

- name: Run the provisioning step
  shell: chainsaw-ovb --config-file /etc/chainsaw.conf provisioning
  environment:
    OS_USERNAME: '{{ os_username }}'
    OS_PASSWORD: '{{ os_password }}'
    OS_TENANT_NAME: '{{ os_tenant_name }}'
    OS_TENANT_ID: '{{ os_tenant_id }}'
    OS_AUTH_URL: '{{ os_auth_url }}'
